# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-01-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160116_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='automodel',
            name='author',
            field=models.CharField(default='anonymous', max_length=255),
        ),
    ]
